name: Build and Deploy

on:
  push:
    branches:
      - "main"
    tags:
      - "*"

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set platform
        run: |
          if [ ${{ matrix.os }} == 'macOS-latest' ]; then
            echo "platform=linux" >> $GITHUB_ENV
          elif [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            echo "platform=macos" >> $GITHUB_ENV
          fi

      - name: Install VLC
        run: |
          if [ ${{ matrix.os }} == 'macOS-latest' ]; then
            brew install vlc --cask
          elif [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            sudo apt-get install vlc
          fi

      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0

      - name: Set version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          sed -i "s/1.0.0/$MAJOR.$MINOR.$PATCH/" ./src/skiptro_ext.lua

      - name: Build
        run: |
          mkdir dist
          cp "${{ github.workspace }}/src/skiptro_ext.lua" dist/
          cat "${{ github.workspace }}/src/skiptro_ext.lua"

          vlc -I luaintf --lua-intf luac --lua-config 'luac={input="${{ github.workspace }}/src/skiptro_ext.lua",output="${{ github.workspace }}/dist/skiptro_ext.luac"}'
          vlc -I luaintf --lua-intf luac --lua-config 'luac={input="${{ github.workspace }}/src/skiptro_intf.lua",output="${{ github.workspace }}/dist/skiptro_intf.luac"}'

      - name: Upload plugin
        uses: actions/upload-artifact@v2
        with:
          name: "skiptro-vlc-${{ env.platform }}"
          path: dist
